import random

#questions

quiz = {
"What is 2 + 2?": "4",
"What is 5 * 3?": "15",
"What is 10 - 4?": "6",
"What is 9 + 8?": "17",
"What is 12 / 3?": "4",
"What is the capital of India?": "Delhi",
"What is the capital of Japan?": "Tokyo",
"What is the capital of France?": "Paris",
"Which continent is India in?": "Asia",
"What is the largest ocean?": "Pacific",
"What planet do we live on?": "Earth",
"Which gas do humans breathe?": "Oxygen",
"What is H2O called?": "Water",
"Which planet is the Red Planet?": "Mars",
"What force pulls objects to Earth?": "Gravity",
"What does CPU stand for?": "Central Processing Unit",
"What does RAM stand for?": "Random Access Memory",
"What does AI stand for?": "Artificial Intelligence",
"What device is used to type?": "Keyboard",
"What device shows output?": "Monitor",
"What is the past tense of go?": "Went",
"What is the plural of child?": "Children",
"What is the synonym of big?": "Large",
"What is the opposite of hot?": "Cold",
"What is the noun in 'Ram runs fast'?": "Ram",
"What comes next: 2,4,6,8 ?": "10",
"What comes next: 5,10,15 ?": "20",
"What comes next: A,B,C ?": "D",
"What comes next: 1,1,2,3 ?": "5",
"What comes next: 3,6,9 ?": "12",
"What is 2 + 2?": "4",
"What is 3 + 3?": "6",
"What is 4 + 4?": "8",
"What is 5 + 5?": "10",
"What is 6 + 6?": "12",
"What is 7 + 7?": "14",
"What is 8 + 8?": "16",
"What is 9 + 9?": "18",
"What is 10 + 10?": "20",
"What is 11 + 11?": "22",
"What is 12 + 12?": "24",
"What is 13 + 13?": "26",
"What is 14 + 14?": "28",
"What is 15 + 15?": "30",
"What is 16 + 16?": "32",
"What is 17 + 17?": "34",
"What is 18 + 18?": "36",
"What is 19 + 19?": "38",
"What is 20 + 20?": "40",
"What is 21 + 21?": "42",
"What is 22 + 22?": "44",
"What is 23 + 23?": "46",
"What is 24 + 24?": "48",
"What is 25 + 25?": "50",
"What is 26 + 26?": "52",
"What is 27 + 27?": "54",
"What is 28 + 28?": "56",
"What is 29 + 29?": "58",
"What is 30 + 30?": "60",
"What is 31 + 31?": "62",
"What is 32 + 32?": "64",
"What is 33 + 33?": "66",
"What is 34 + 34?": "68",
"What is 35 + 35?": "70",
"What is 36 + 36?": "72",
"What is 37 + 37?": "74",
"What is 38 + 38?": "76",
"What is 39 + 39?": "78",
"What is 40 + 40?": "80",
"What is 41 + 41?": "82",
"What is 42 + 42?": "84",
"What is 43 + 43?": "86",
"What is 44 + 44?": "88",
"What is 45 + 45?": "90",
"What is 46 + 46?": "92",
"What is 47 + 47?": "94",
"What is 48 + 48?": "96",
"What is 49 + 49?": "98",
"What is 50 + 50?": "100",
"What is 51 + 51?": "102",
"What is 52 + 52?": "104",
"What is 53 + 53?": "106",
"What is 54 + 54?": "108",
"What is 55 + 55?": "110",
"What is 56 + 56?": "112",
"What is 57 + 57?": "114",
"What is 58 + 58?": "116",
"What is 59 + 59?": "118",
"What is 60 + 60?": "120",
"What is 61 + 61?": "122",
"What is 62 + 62?": "124",
"What is 63 + 63?": "126",
"What is 64 + 64?": "128",
"What is 65 + 65?": "130",
"What is 66 + 66?": "132",
"What is 67 + 67?": "134",
"What is 68 + 68?": "136",
"What is 69 + 69?": "138",
"What is 70 + 70?": "140",
"What is 71 + 71?": "142",
"What is 72 + 72?": "144",
"What is 73 + 73?": "146",
"What is 74 + 74?": "148",
"What is 75 + 75?": "150",
"What is 76 + 76?": "152",
"What is 77 + 77?": "154",
"What is 78 + 78?": "156",
"What is 79 + 79?": "158",
"What is 80 + 80?": "160",
"What is 81 + 81?": "162",
"What is 82 + 82?": "164",
"What is 83 + 83?": "166",
"What is 84 + 84?": "168",
"What is 85 + 85?": "170",
"What is 86 + 86?": "172",
"What is 87 + 87?": "174",
"What is 88 + 88?": "176",
"What is 89 + 89?": "178",
"What is 90 + 90?": "180",
"What is 91 + 91?": "182",
"What is 92 + 92?": "184",
"What is 93 + 93?": "186",
"What is 94 + 94?": "188",
"What is 95 + 95?": "190",
"What is 96 + 96?": "192",
"What is 97 + 97?": "194",
"What is 98 + 98?": "196",
"What is 99 + 99?": "198",
"What is 100 + 100?": "200",
"What is the capital of India?": "Delhi",
"What is the capital of Japan?": "Tokyo",
"What is the capital of France?": "Paris",
"What is the capital of Germany?": "Berlin",
"What is the capital of Italy?": "Rome",
"What is the capital of China?": "Beijing",
"What is the capital of Russia?": "Moscow",
"What is the capital of USA?": "Washington",
"What is the capital of Bangladesh?": "Dhaka",
"What is the capital of Nepal?": "Kathmandu",
"Who is known as the Father of the Nation in India?": "Mahatma Gandhi",
"Who invented the telephone?": "Alexander Graham Bell",
"Who invented the light bulb?": "Thomas Edison",
"Who discovered gravity?": "Isaac Newton",
"Who discovered penicillin?": "Alexander Fleming",
"What is the largest planet?": "Jupiter",
"What is the smallest planet?": "Mercury",
"What planet do we live on?": "Earth",
"What is the hottest planet?": "Venus",
"What is the red planet?": "Mars",
"What gas do plants take in?": "Carbon Dioxide",
"What gas do humans breathe in?": "Oxygen",
"What is the chemical formula of water?": "H2O",
"What star is closest to Earth?": "Sun",
"What is the center of our solar system?": "Sun",
"Which is the largest ocean?": "Pacific Ocean",
"Which is the smallest ocean?": "Arctic Ocean",
"Which is the largest continent?": "Asia",
"Which is the smallest continent?": "Australia",
"Which desert is the largest?": "Sahara",
"What is the national animal of India?": "Tiger",
"What is the national bird of India?": "Peacock",
"What is the national flower of India?": "Lotus",
"What is the national fruit of India?": "Mango",
"What is the national tree of India?": "Banyan",
"Who was the first President of India?": "Rajendra Prasad",
"Who was the first Prime Minister of India?": "Jawaharlal Nehru",
"Who is known as the Iron Man of India?": "Sardar Patel",
"Who wrote the national anthem of India?": "Rabindranath Tagore",
"What is the fastest land animal?": "Cheetah",
"What is the tallest animal?": "Giraffe",
"What is the largest animal?": "Blue Whale",
"Which bird cannot fly?": "Ostrich",
"Which animal is known as man's best friend?": "Dog",
"What is the currency of India?": "Rupee",
"What is the currency of USA?": "Dollar",
"What is the currency of Japan?": "Yen",
"What is the currency of UK?": "Pound",
"What is the largest river in India?": "Ganga",
"What is the longest river in the world?": "Nile",
"What mountain is the tallest in the world?": "Mount Everest",
"Where is Mount Everest located?": "Nepal",
"Which festival is known as the festival of lights?": "Diwali",
"Which festival is known as the festival of colors?": "Holi",
"Which festival is celebrated by Muslims after Ramadan?": "Eid",
"Which festival celebrates the birth of Jesus?": "Christmas",
"What is the largest country by area?": "Russia",
"What is the most populous country?": "China",
"Which continent has the most countries?": "Africa",
"What device is used to measure temperature?": "Thermometer",
"What device is used to measure time?": "Clock",
"What device is used to measure weight?": "Weighing Scale",
"What device is used to measure distance?": "Meter",
"Which metal is liquid at room temperature?": "Mercury",
"What metal is used in electric wires?": "Copper",
"What gas do plants release?": "Oxygen",
"What vitamin do we get from sunlight?": "Vitamin D",
"What is the largest island?": "Greenland",
"What is the deepest ocean point?": "Mariana Trench",
"What is the largest lake?": "Caspian Sea",
"Who wrote the Ramayana?": "Valmiki",
"Who wrote the Mahabharata?": "Ved Vyasa",
"Who wrote Harry Potter?": "J K Rowling",
"What is the fastest bird?": "Peregrine Falcon",
"What animal is known as the king of the jungle?": "Lion",
"What is the study of plants called?": "Botany",
"What is the study of animals called?": "Zoology",
"What is the study of the earth called?": "Geology",
"What is the capital of West Bengal?": "Kolkata",
"What river flows through Kolkata?": "Hooghly",
"Which sport uses a bat and ball in India?": "Cricket",
"Which country started the Olympic Games?": "Greece",
"What is the largest organ of the human body?": "Skin",
"What organ pumps blood?": "Heart",
"What organ helps us breathe?": "Lungs",
"What is the boiling point of water?": "100",
"What is the freezing point of water?": "0",
"What color is chlorophyll?": "Green",
"What part of plant makes food?": "Leaf",
"What is the national sport of India?": "Hockey",
"What is the biggest festival in India?": "Diwali",
"Which direction does the sun rise?": "East",
"Which direction does the sun set?": "West",
"What is the speed of light?": "300000 km/s",
"What gas do plants use in photosynthesis?": "Carbon Dioxide",
"What gas do plants release?": "Oxygen",
"What is H2O?": "Water",
"What is the chemical symbol of Oxygen?": "O",
"What is the chemical symbol of Hydrogen?": "H",
"What is the chemical symbol of Sodium?": "Na",
"What is the chemical symbol of Iron?": "Fe",
"What is the chemical symbol of Gold?": "Au",
"What is the chemical symbol of Silver?": "Ag",
"What organ pumps blood in the human body?": "Heart",
"What organ helps us breathe?": "Lungs",
"What organ controls the body?": "Brain",
"What is the largest organ in the human body?": "Skin",
"What is the smallest bone in the human body?": "Stapes",
"What is the boiling point of water?": "100",
"What is the freezing point of water?": "0",
"What force pulls objects toward Earth?": "Gravity",
"Who discovered gravity?": "Isaac Newton",
"What is the unit of force?": "Newton",
"What planet is known as the red planet?": "Mars",
"What is the largest planet?": "Jupiter",
"What is the smallest planet?": "Mercury",
"What star gives us light and heat?": "Sun",
"What galaxy do we live in?": "Milky Way",
"What part of plant makes food?": "Leaf",
"What pigment makes plants green?": "Chlorophyll",
"What part of plant absorbs water?": "Root",
"What part of plant makes seeds?": "Flower",
"What vitamin do we get from sunlight?": "Vitamin D",
"What vitamin helps eyesight?": "Vitamin A",
"What vitamin helps blood clotting?": "Vitamin K",
"What is the study of plants called?": "Botany",
"What is the study of animals called?": "Zoology",
"What is the study of microorganisms called?": "Microbiology",
"What gas is most abundant in air?": "Nitrogen",
"What gas helps burning?": "Oxygen",
"What gas is used in balloons?": "Helium",
"What instrument measures temperature?": "Thermometer",
"What instrument measures pressure?": "Barometer",
"What instrument measures electric current?": "Ammeter",
"What is the unit of electricity?": "Watt",
"What is the unit of energy?": "Joule",
"What is the unit of temperature?": "Celsius",
"What metal is liquid at room temperature?": "Mercury",
"What metal is used in electric wires?": "Copper",
"What metal is used in jewellery?": "Gold",
"What blood cells fight infection?": "White Blood Cells",
"What blood cells carry oxygen?": "Red Blood Cells",
"What is the powerhouse of the cell?": "Mitochondria",
"What is the basic unit of life?": "Cell",
"What carries genetic information?": "DNA",
"What is the fastest land animal?": "Cheetah",
"What is the largest animal?": "Blue Whale",
"What bird cannot fly?": "Ostrich",
"What layer protects Earth from UV rays?": "Ozone Layer",
"What is the center of the solar system?": "Sun",
"What gas causes global warming?": "Carbon Dioxide",
"What renewable energy comes from the sun?": "Solar Energy",
"What renewable energy comes from wind?": "Wind Energy",
"Who was the first President of India?": "Rajendra Prasad",
"Who was the first Prime Minister of India?": "Jawaharlal Nehru",
"Who is known as the Father of the Nation in India?": "Mahatma Gandhi",
"Who was the first Mughal emperor?": "Babur",
"Who built the Taj Mahal?": "Shah Jahan",
"Who was known as the Iron Man of India?": "Sardar Patel",
"Who was the last Mughal emperor?": "Bahadur Shah Zafar",
"Who founded the Maurya Empire?": "Chandragupta Maurya",
"Who was the teacher of Chandragupta Maurya?": "Chanakya",
"Who was the greatest Mauryan emperor?": "Ashoka",
"Which war established British rule in India?": "Battle of Plassey",
"In which year did India get independence?": "1947",
"Who was the first Governor General of independent India?": "C Rajagopalachari",
"Who gave the slogan 'Do or Die'?": "Mahatma Gandhi",
"Who led the Salt March?": "Mahatma Gandhi",
"Who discovered America?": "Christopher Columbus",
"Who was the first man to travel around the world?": "Ferdinand Magellan",
"Who was the first Emperor of Rome?": "Augustus",
"Who was the famous queen of Egypt?": "Cleopatra",
"Who was the leader of Nazi Germany?": "Adolf Hitler",
"Which war was fought between 1914 and 1918?": "World War 1",
"Which war was fought between 1939 and 1945?": "World War 2",
"Who was the Prime Minister of Britain during World War 2?": "Winston Churchill",
"Who was the founder of Buddhism?": "Gautama Buddha",
"Who founded Jainism?": "Mahavira",
"Who started the Mughal Empire in India?": "Babur",
"Who built the Red Fort?": "Shah Jahan",
"Who built Qutub Minar?": "Qutb ud din Aibak",
"Who was the founder of the Gupta Empire?": "Chandragupta I",
"Who was the greatest Gupta ruler?": "Samudragupta",
"Who wrote the Ramayana?": "Valmiki",
"Who wrote the Mahabharata?": "Ved Vyasa",
"Who was the founder of the Delhi Sultanate?": "Qutb ud din Aibak",
"Who was the founder of the Khilji dynasty?": "Jalaluddin Khilji",
"Who was the founder of the Tughlaq dynasty?": "Ghiyasuddin Tughlaq",
"Who was the founder of the Maratha Empire?": "Shivaji",
"Who defeated Napoleon at Waterloo?": "Duke of Wellington",
"Who was the first woman Prime Minister of India?": "Indira Gandhi",
"Who wrote the Indian national anthem?": "Rabindranath Tagore",
"Who gave the slogan 'Jai Hind'?": "Subhas Chandra Bose",
"Who founded the Indian National Congress?": "A O Hume",
"Who was the first woman President of India?": "Pratibha Patil",
"Who was the first Indian to go to space?": "Rakesh Sharma",
"Who was the first woman to go to space?": "Valentina Tereshkova",
"Who was the first man on the Moon?": "Neil Armstrong",
"In which year did World War 2 end?": "1945",
"In which year did World War 1 begin?": "1914",
"Which civilization built the pyramids?": "Egyptian",
"Which river was important for Egyptian civilization?": "Nile",
"Which civilization developed along the Indus River?": "Indus Valley Civilization",
"Who discovered sea route to India?": "Vasco da Gama",
"Who founded the British East India Company?": "British Traders",
"Who was the last Governor General of British India?": "Lord Mountbatten",
"Which movement started in 1942?": "Quit India Movement",
"Which movement started in 1920?": "Non Cooperation Movement",
"Which movement started in 1930?": "Civil Disobedience Movement",
"What comes next: 2, 4, 6, 8, ?": "10",
"What comes next: 5, 10, 15, 20, ?": "25",
"What comes next: 3, 6, 9, 12, ?": "15",
"What comes next: 7, 14, 21, 28, ?": "35",
"What comes next: 1, 3, 5, 7, ?": "9",
"What comes next: 10, 20, 30, 40, ?": "50",
"What comes next: 4, 8, 12, 16, ?": "20",
"What comes next: 6, 12, 18, 24, ?": "30",
"What comes next: 9, 18, 27, 36, ?": "45",
"What comes next: 11, 22, 33, 44, ?": "55",
"What comes next: 1, 4, 9, 16, ?": "25",
"What comes next: 2, 5, 10, 17, ?": "26",
"What comes next: 3, 9, 27, ?": "81",
"What comes next: 2, 6, 18, ?": "54",
"What is the odd one out: Dog, Cat, Tiger, Car": "Car",
"What is the odd one out: Apple, Mango, Banana, Car": "Car",
"What is the odd one out: Cow, Goat, Lion, Table": "Table",
"Complete the analogy: Cat : Kitten :: Dog : ?": "Puppy",
"Complete the analogy: Man : Boy :: Woman : ?": "Girl",
"Complete the analogy: King : Queen :: Man : ?": "Woman",
"If today is Monday, what day comes after 3 days?": "Thursday",
"If today is Friday, what day comes after 2 days?": "Sunday",
"If today is Sunday, what day comes after 1 day?": "Monday",
"If 5 + 3 = 28 and 6 + 4 = 46 then 7 + 5 = ?": "70",
"If A = 1, B = 2 then C = ?": "3",
"If A = 1, B = 2 then Z = ?": "26",
"What is half of 50?": "25",
"What is double of 21?": "42",
"What number is between 30 and 32?": "31",
"What comes next: A, B, C, D, ?": "E",
"What comes next: J, K, L, M, ?": "N",
"What comes next: W, X, Y, ?": "Z",
"What comes next: Z, Y, X, W, ?": "V",
"What comes next: 100, 90, 80, 70, ?": "60",
"What comes next: 50, 45, 40, 35, ?": "30",
"What is the square of 9?": "81",
"What is the cube of 3?": "27",
"What is the square of 12?": "144",
"What number is missing: 2, ?, 6, 8": "4",
"What number is missing: 5, ?, 15, 20": "10",
"What number is missing: 3, ?, 9, 12": "6",
"What does CPU stand for?": "Central Processing Unit",
"What does RAM stand for?": "Random Access Memory",
"What does ROM stand for?": "Read Only Memory",
"What does GPU stand for?": "Graphics Processing Unit",
"What does USB stand for?": "Universal Serial Bus",
"Who is known as the father of computer?": "Charles Babbage",
"Who founded Microsoft?": "Bill Gates",
"Who founded Apple?": "Steve Jobs",
"Who founded Facebook?": "Mark Zuckerberg",
"What does WWW stand for?": "World Wide Web",
"What does URL stand for?": "Uniform Resource Locator",
"What does HTML stand for?": "Hyper Text Markup Language",
"What does CSS stand for?": "Cascading Style Sheets",
"What is the brain of the computer?": "CPU",
"What device is used to type text?": "Keyboard",
"What device is used to move the cursor?": "Mouse",
"What device displays output?": "Monitor",
"What device prints documents?": "Printer",
"What storage device is used to store data permanently?": "Hard Disk",
"What storage device is portable and uses USB?": "Pen Drive",
"What storage device uses optical technology?": "CD",
"What is the full form of AI?": "Artificial Intelligence",
"What is the full form of ML?": "Machine Learning",
"What is the full form of IT?": "Information Technology",
"What company created Windows?": "Microsoft",
"What company created Android?": "Google",
"What company created iPhone?": "Apple",
"What programming language is used for web pages?": "HTML",
"What programming language is known for AI?": "Python",
"What key is used to delete text?": "Delete",
"What key is used to move to next line?": "Enter",
"What key is used for space?": "Spacebar",
"What is the main circuit board of a computer?": "Motherboard",
"What part stores temporary data?": "RAM",
"What part stores permanent data?": "Hard Disk",
"What is an operating system?": "System Software",
"Name an operating system by Microsoft": "Windows",
"Name an operating system by Apple": "macOS",
"Name an operating system by Google": "Android",
"What is used to browse websites?": "Browser",
"Name a popular web browser": "Chrome",
"What device connects computers to internet?": "Router",
"What network covers a small area?": "LAN",
"What network covers a large area?": "WAN",
"What symbol is used in email address?": "@",
"What company owns YouTube?": "Google",
"What language is mainly used for data science?": "Python",
"What language is used for Android apps?": "Java",
"What language is used for web styling?": "CSS",
"What is the plural of 'child'?": "Children",
"What is the plural of 'man'?": "Men",
"What is the plural of 'woman'?": "Women",
"What is the plural of 'mouse'?": "Mice",
"What is the plural of 'tooth'?": "Teeth",
"What is the past tense of 'go'?": "Went",
"What is the past tense of 'eat'?": "Ate",
"What is the past tense of 'run'?": "Ran",
"What is the past tense of 'write'?": "Wrote",
"What is the past tense of 'see'?": "Saw",
"What is the comparative form of 'good'?": "Better",
"What is the superlative form of 'good'?": "Best",
"What is the comparative form of 'bad'?": "Worse",
"What is the superlative form of 'bad'?": "Worst",
"Fill in the blank: She ___ going to school": "Is",
"Fill in the blank: They ___ playing football": "Are",
"Fill in the blank: I ___ a student": "Am",
"Fill in the blank: He ___ eating an apple": "Is",
"Fill in the blank: We ___ happy today": "Are",
"Fill in the blank: I ___ reading a book": "Am",
"What is the opposite of 'big'?": "Small",
"What is the opposite of 'hot'?": "Cold",
"What is the opposite of 'happy'?": "Sad",
"What is the opposite of 'fast'?": "Slow",
"What is the synonym of 'happy'?": "Joyful",
"What is the synonym of 'big'?": "Large",
"What is the synonym of 'small'?": "Tiny",
"What is the synonym of 'fast'?": "Quick",
"What part of speech is 'run'?": "Verb",
"What part of speech is 'beautiful'?": "Adjective",
"What part of speech is 'quickly'?": "Adverb",
"What part of speech is 'book'?": "Noun",
"Fill in the blank: She ___ a doctor": "Is",
"Fill in the blank: They ___ students": "Are",
"Fill in the blank: I ___ tired": "Am",
"Fill in the blank: He ___ football every day": "Plays",
"Fill in the blank: She ___ English well": "Speaks",
"Fill in the blank: Birds ___ in the sky": "Fly",
"Choose correct article: ___ apple": "An",
"Choose correct article: ___ boy": "A",
"Choose correct article: ___ elephant": "An",
"Fill in the blank: I live ___ India": "In",
"Fill in the blank: The book is ___ the table": "On",
"Fill in the blank: The cat is ___ the box": "In",
"Fill in the blank: She is afraid ___ dogs": "Of",
"Fill in the blank: He is fond ___ music": "Of",
"Fill in the blank: I am going ___ school": "To",
"Fill in the blank: She came ___ home": "Back",
"What is the plural of 'foot'?": "Feet",
"What is the plural of 'goose'?": "Geese",
"Fill in the blank: He ___ a car": "Has",
"Fill in the blank: They ___ many books": "Have",
"What is the past tense of 'buy'?": "Bought",
"What is the past tense of 'bring'?": "Brought",
"What is the past tense of 'teach'?": "Taught",
"What is 5 + 7?": "12",
"What is 9 * 3?": "27",
"What is 15 - 6?": "9",
"What is 8 * 8?": "64",
"What is the square of 9?": "81",
"What is the capital of India?": "Delhi",
"What is the capital of Japan?": "Tokyo",
"What is the largest planet?": "Jupiter",
"What is the smallest planet?": "Mercury",
"What is the red planet?": "Mars",
"What gas do plants take in?": "Carbon Dioxide",
"What gas do humans breathe?": "Oxygen",
"What is the chemical formula of water?": "H2O",
"What vitamin do we get from sunlight?": "Vitamin D",
"What organ pumps blood?": "Heart",
"Who discovered gravity?": "Isaac Newton",
"Who built the Taj Mahal?": "Shah Jahan",
"Who was the first Prime Minister of India?": "Jawaharlal Nehru",
"Who wrote the national anthem of India?": "Rabindranath Tagore",
"In which year did India get independence?": "1947",
"What does CPU stand for?": "Central Processing Unit",
"What does RAM stand for?": "Random Access Memory",
"What does HTML stand for?": "Hyper Text Markup Language",
"What company created Windows?": "Microsoft",
"What company created Android?": "Google",
"What comes next: 2, 4, 6, 8, ?": "10",
"What comes next: 5, 10, 15, 20, ?": "25",
"What comes next: A, B, C, D, ?": "E",
"What comes next: Z, Y, X, W, ?": "V",
"What is half of 50?": "25",
"What is the plural of 'child'?": "Children",
"What is the plural of 'man'?": "Men",
"What is the past tense of 'go'?": "Went",
"What is the past tense of 'eat'?": "Ate",
"What is the opposite of 'big'?": "Small",
"What is the fastest land animal?": "Cheetah",
"What is the largest animal?": "Blue Whale",
"What is the national animal of India?": "Tiger",
"What is the national bird of India?": "Peacock",
"What is the national flower of India?": "Lotus",
"What instrument measures temperature?": "Thermometer",
"What instrument measures pressure?": "Barometer",
"What metal is liquid at room temperature?": "Mercury",
"What metal is used in electric wires?": "Copper",
"What is the study of plants called?": "Botany",
"What device is used to type text?": "Keyboard",
"What device is used to move the cursor?": "Mouse",
"What device prints documents?": "Printer",
"What storage device is portable and uses USB?": "Pen Drive",
"What language is popular for AI?": "Python",
"What is the square root of 144?": "12",
"What is the square root of 225?": "15",
"What is the square root of 400?": "20",
"What is the cube of 12?": "1728",
"What is the cube root of 27?": "3",
"What is 15^2 ?": "225",
"What is 25^2 ?": "625",
"What is 12^3 ?": "1728",
"What is 13^2 ?": "169",
"What is 17^2 ?": "289",
"What is 7 * 13 ?": "91",
"What is 12 * 14 ?": "168",
"What is 15 * 16 ?": "240",
"What is 18 * 12 ?": "216",
"What is 21 * 11 ?": "231",
"What is the value of 3^4 ?": "81",
"What is the value of 2^6 ?": "64",
"What is the value of 5^3 ?": "125",
"What is the value of 10^3 ?": "1000",
"What is the value of 100 ÷ 4 ?": "25",
"What is the value of 144 ÷ 12 ?": "12",
"What is the value of 225 ÷ 15 ?": "15",
"What is the value of 121 ÷ 11 ?": "11",
"What is the LCM of 4 and 6?": "12",
"What is the LCM of 6 and 8?": "24",
"What is the LCM of 9 and 12?": "36",
"What is the HCF of 12 and 18?": "6",
"What is the HCF of 20 and 30?": "10",
"What is the HCF of 16 and 24?": "8",
"What is 25% of 200?": "50",
"What is 10% of 500?": "50",
"What is 50% of 80?": "40",
"What is 75% of 200?": "150",
"What is the perimeter of a square with side 5?": "20",
"What is the area of a square with side 6?": "36",
"What is the area of a rectangle with length 8 and width 5?": "40",
"What is the perimeter of a rectangle with length 10 and width 4?": "28",
"What is the value of 2 + 3 * 4 ?": "14",
"What is the value of (2 + 3) * 4 ?": "20",
"What is the value of 10^2 ?": "100",
"What is the value of 11^2 ?": "121",
"What is the value of 14^2 ?": "196",
"What is the square root of 169?": "13",
"What is the square root of 196?": "14",
"What is the square root of 256?": "16",
"What is the cube root of 64?": "4",
"What is the cube root of 125?": "5"
}

#grade calculating
def grade_calculator(percentage):
    if percentage >= 90:
        return "Excellent"
    elif percentage >= 80:
        return "A"
    elif percentage >= 70:
        return "B"
    elif percentage >= 60:
        return "C"
    elif percentage >= 50:
        return "D"
    else:
        return "F"


# main quiz
def play_quiz():
    score = 0

   #convert dict to list
    questions = list(quiz.items())
    random.shuffle(questions)

    total_questions = min(10, len(questions))

    print("\n" + " QUIZ GAME ".center(60, "-"))

    for i in range(total_questions):

        question, correct_answer = questions[i]

        print(f"\nQuestion {i + 1}: {question}")

        user_answer = input("Your Answer: ").strip()

        # Case-insensitive comparison
        if user_answer.strip().lower() == correct_answer.strip().lower():
            print("Correct! ")
            score += 1
        else:
            print(f"Wrong! Correct Answer: {correct_answer}")

    # Final Result
    percentage = (score / total_questions) * 100
    grade = grade_calculator(percentage)

    print("\n" + " RESULT ".center(60, "="))
    print(f"Score      : {score}/{total_questions}")
    print(f"Percentage : {percentage:.2f}%")
    print(f"Grade      : {grade}")
    print("=" * 60)
#main program
def main():
    print("\n"+"Welcome to Quiz Game".center(80,"-"))
    while True:
        play_quiz()
        choice = input("Are you want to play again (Y/N):").strip().upper()
        if choice == "Y":
            print("Yes")
            continue
        elif choice == "N":
            print("\nThank You for Playing!")
            break
        else:
            print("Please Enter Y or N")
            continue

#run the program
main()

